server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://47.104.7.130:3306/mistress
    username: root
    password: yuchao428
    type: com.alibaba.druid.pool.DruidDataSource
  cache:
    cache-names: c1,c2
    redis:
      time-to-live: 1800s
  redis:
    database: 0
    password: yuchao428
    port: 6379
    host: 47.104.7.130
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
      shutdown-timeout: 100ms
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
    check-template: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: false
  rabbitmq:
    addresses: 47.104.7.130
    port: 5672
    username: mozzior
    password: yuchao428
